version: 1.2
workflows:
   - name: "TOBIAS"
     subclass: WDL
     primaryDescriptorPath: /TOBIAS.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
         tags:
             - /.*/

